<?php

use Illuminate\Database\Seeder;

class RoutesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('routes')->delete();
        
        \DB::table('routes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => '2017-08-10 00:20:58',
                'updated_at' => '2017-08-10 08:59:09',
                'sector_id' => 1,
                'location_id' => 1,
            'conquistadores' => 'Arthur Acastro Egg (Tuco) e Alexandre Lorenzetto (Sassá)',
                'anoConquista' => '1997',
                'tipo' => 'Esportiva',
                'nome' => 'Bienal',
                'descricao' => 'Linda via com lances em aderência e regletes seguindo em diagonal para a direita, com excelente movimentação. Escalada com belo visual.',
                'exposicao' => 'E1',
                'graduacao' => 'VIIb',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '1',
                'protecao' => 'Chapeletas',
                'material' => '4 costuras',
                'dicas' => '',
                'croqui' => NULL,
                'fonteDados' => 'Guia de Escalada do Morro do Canal',
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => '2017-08-10 00:53:16',
                'updated_at' => '2017-08-10 08:59:01',
                'sector_id' => 2,
                'location_id' => 2,
                'conquistadores' => '',
                'anoConquista' => '',
                'tipo' => 'Boulder',
                'nome' => 'Preamar',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => 'VIIb',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => NULL,
                'fonteDados' => 'Guia de escaladas em rocha - São Francisco do Sul',
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => '2017-08-10 00:54:30',
                'updated_at' => '2017-08-10 08:58:11',
                'sector_id' => 2,
                'location_id' => 2,
                'conquistadores' => '',
                'anoConquista' => '',
                'tipo' => 'Boulder',
                'nome' => 'Fissurados',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => 'VIsup',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => NULL,
                'fonteDados' => 'Guia de escaladas em rocha - São Francisco do Sul',
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => '2017-08-10 07:53:46',
                'updated_at' => '2017-08-10 08:58:47',
                'sector_id' => 1,
                'location_id' => 1,
            'conquistadores' => 'Carlos Michel (Carlera) e José Luis Verbiski (Capachão)',
                'anoConquista' => '1998',
                'tipo' => 'Esportiva',
                'nome' => 'Cachorro Loko',
                'descricao' => 'Via com saída em regletes. Em seguida, passa por um balcão maroto que pode proporcionar belos vôos. Excelente.',
                'exposicao' => 'E1',
                'graduacao' => 'VIIc',
                'crux' => '',
                'altura' => '20',
                'enfiadas' => '1',
                'protecao' => 'Chapeletas',
                'material' => '5 costuras',
                'dicas' => '',
                'croqui' => NULL,
                'fonteDados' => 'Guia de escalada do Morro do Canal',
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => '2017-08-10 08:00:35',
                'updated_at' => '2017-08-10 08:58:25',
                'sector_id' => 3,
                'location_id' => 1,
                'conquistadores' => 'Andrey Romaniuk e Paulo Haiduke',
                'anoConquista' => '2013',
                'tipo' => 'Esportiva',
                'nome' => 'Fábulas e Tragédias',
                'descricao' => 'Divertida linha em aderência, com dois crux bem definidos na parte mais empinada da parede. Após a última chapa, segue pela rampa em esticão até a parada da via Super Aderência.',
                'exposicao' => 'E1',
                'graduacao' => 'V',
                'crux' => '',
                'altura' => '30',
                'enfiadas' => '1',
                'protecao' => 'Chapeletas',
                'material' => '4 costuras',
                'dicas' => 'O rapel deve ser feito com corda de 60 metros.',
                'croqui' => NULL,
                'fonteDados' => 'Guia de escalada do Morro do Canal',
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:25:24',
                'sector_id' => 8,
                'location_id' => 4,
                'conquistadores' => 'Antônio Carlos Schmall Moreira, Carlos Eduardo "Tozóide", Dálio Zippin Neto, Dino J.A. Camargo, Domingos Alvarez, Fábio Sceszniak, Ivan O. V. Ribeiro, José Luiz Hartmann "Chiquinho", Júlio Nogueira, Lothário Stoltz "Kikko", Milton Pieffer "Snake", Pedro Hartmann, Ronaldo Franzen "Nativo"',
                'anoConquista' => '1987',
                'tipo' => 'Tradicional',
                'nome' => 'Mar de Caratuvas',
                'descricao' => '',
                'exposicao' => 'E4',
                'graduacao' => 'V',
                'crux' => 'Vsup',
                'altura' => '550',
                'enfiadas' => '14',
                'protecao' => 'Mista',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/9f2bb4e6776e8ef7baf387a3e9e0bb33.pdf',
                'fonteDados' => 'rumos.net.br',
            ),
            6 => 
            array (
                'id' => 20,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Carlos Alberto, Leonardo, Luciano, Margarida e Santa Cruz',
                'anoConquista' => '1986',
                'tipo' => 'Esportiva',
                'nome' => 'Augusto Ruschi',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2° II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0016.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            7 => 
            array (
                'id' => 47,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Jacques Cardeman, Pedro Ary, Sérgio Gonçalves e Daniel Gonçalves. ',
                'anoConquista' => '1993',
                'tipo' => 'Esportiva',
                'nome' => 'Confusões Alucinogenas',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '1° Is',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0048.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            8 => 
            array (
                'id' => 54,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Jacques Cardeman, Yuri Marx, Cristian Chagas e Michel Cipolatti. ',
                'anoConquista' => '1994',
                'tipo' => 'Esportiva',
                'nome' => 'Degradê, Variante',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '3° IV',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0060.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            9 => 
            array (
                'id' => 151,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => '',
                'anoConquista' => '1974',
                'tipo' => 'Esportiva',
                'nome' => 'Verde, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '1° II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0181.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            10 => 
            array (
                'id' => 156,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Carlos Bernardo e Salomyth Fernandes',
                'anoConquista' => '1974',
                'tipo' => 'Esportiva',
                'nome' => 'Vermelho, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2° IV',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0187.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            11 => 
            array (
                'id' => 192,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Giuseppe Pellegrini e Reinaldo Pires',
                'anoConquista' => '1975',
                'tipo' => 'Esportiva',
                'nome' => 'Azul, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2° II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0237.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            12 => 
            array (
                'id' => 194,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Félis Pires e Luiz Otávio Cardoso',
                'anoConquista' => '1975',
                'tipo' => 'Esportiva',
                'nome' => 'Preto, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2° II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0239.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            13 => 
            array (
                'id' => 229,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'André Ilha e Gabriel Fonseca',
                'anoConquista' => '1994',
                'tipo' => 'Esportiva',
                'nome' => 'Cabeça Oca, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => 'Vsup',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0277.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            14 => 
            array (
                'id' => 249,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Antônio Carlos Magalhães, Ricardo de Morais Almeida e Anthony David Adler',
                'anoConquista' => '1978',
                'tipo' => 'Esportiva',
                'nome' => 'Apocalipse, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '4° IV',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0297.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            15 => 
            array (
                'id' => 250,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Antonio Carlos Magalhães e Paulo Roberto. P. Ferreira',
                'anoConquista' => '',
                'tipo' => 'Esportiva',
                'nome' => 'Daltônico, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2° II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0298.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            16 => 
            array (
                'id' => 332,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Cláudio Fon-Fon Fontenelle, Eduardo Hutter, Félis Pires, Luís Carlos, Márcia Leuzinger e Paulo Roberto Rosa',
                'anoConquista' => '1981',
                'tipo' => 'Esportiva',
                'nome' => 'Três Patetas',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2° II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0383.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            17 => 
            array (
                'id' => 333,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Daniel Alvarenga, Felipe Alvarenga, Luis Sayão, Maurício Abdu e Oswaldo Pereira',
                'anoConquista' => '1986',
                'tipo' => 'Esportiva',
                'nome' => 'Cor de Abóbora, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '3°',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0384.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            18 => 
            array (
                'id' => 350,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Mario Arnaud',
                'anoConquista' => '',
                'tipo' => 'Esportiva',
                'nome' => 'Cinza, Paredão',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2°',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0392.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            19 => 
            array (
                'id' => 351,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Felipe Alvarenga, Ricardo Borges, Ricardo Prado e Oswaldo Santa Cruz Pereira',
                'anoConquista' => '1989',
                'tipo' => 'Esportiva',
                'nome' => 'Infravermelho',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2°',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0393.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            20 => 
            array (
                'id' => 357,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Luis Sayão, Marli Ignés e Oswaldo Santa Cruz Pereira',
                'anoConquista' => '1985',
                'tipo' => 'Esportiva',
                'nome' => 'Cor de Burro Quando Foge',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '2°',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0399.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            21 => 
            array (
                'id' => 360,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Alexandre Becker',
                'anoConquista' => '1988',
                'tipo' => 'Esportiva',
                'nome' => 'Gemini Azul',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '3º II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0403.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            22 => 
            array (
                'id' => 361,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Carlos Constanza, Hélio Barroso, José Vargas e Luiz Constanza ',
                'anoConquista' => '1976',
                'tipo' => 'Esportiva',
                'nome' => 'Arco-Íris',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '3º II',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0404.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            23 => 
            array (
                'id' => 413,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Jorge Campos Jr, Paulo Baldner e Ricardo Teixeira',
                'anoConquista' => '2001',
                'tipo' => 'Esportiva',
                'nome' => 'Capitão Virgulino Ferreira, Variante',
                'descricao' => '',
                'exposicao' => '',
                'graduacao' => '3° VI',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0463.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            24 => 
            array (
                'id' => 653,
                'created_at' => '2017-08-15 16:24:15',
                'updated_at' => '2017-08-15 16:24:15',
                'sector_id' => 9,
                'location_id' => 5,
                'conquistadores' => 'Alfredo Neto e João Antônio',
                'anoConquista' => '2000',
                'tipo' => 'Esportiva',
                'nome' => 'Alea Jacta Est, Variante',
                'descricao' => '',
                'exposicao' => 'E4',
                'graduacao' => 'II E4',
                'crux' => '',
                'altura' => '',
                'enfiadas' => '',
                'protecao' => '',
                'material' => '',
                'dicas' => '',
                'croqui' => 'uploads/2017-08/femerj/img0706.pdf',
                'fonteDados' => 'Croquiteca CEC/FEMERJ',
            ),
            25 => 
            array (
                'id' => 654,
                'created_at' => '2017-09-19 13:43:50',
                'updated_at' => NULL,
                'sector_id' => 10,
                'location_id' => 7,
                'conquistadores' => 'Cauí Vieira, Heraldo G, Luciano W',
                'anoConquista' => '2010',
                'tipo' => 'Esportiva',
                'nome' => 'Faixa de Gaza',
                'descricao' => 'A via pode ser dividida em duas partes: chaminé/canaleta vertical e rampões. Na primeira parte sobe-se um trepa-mato até o platô onde se encorda e sobe duas enfiadas de canaletas/chaminé, a primeira protegida com móveis grandes, a segunda em fixo. A partir daí são 3 enfiadas mais expostas, rampões até o cume, e só existem grampos nas paradas, que são simples.',
                'exposicao' => 'E3',
                'graduacao' => 'III',
                'crux' => 'VIsup',
                'altura' => '150',
                'enfiadas' => '3',
                'protecao' => 'Chapeletas',
            'material' => '11 Costuras, 01 corda de 60m, Friends grandes (#4 ao 7)',
                'dicas' => '',
                'croqui' => 'uploads/2017-09/faixadegaza.jpg',
                'fonteDados' => 'Guia de escalada de Brejo da Madre de Deus',
            ),
        ));
        
        
    }
}